return {
  -- treesitter
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "java",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "rust",
        "c",
        "cpp",
        "css",
        "dockerfile",
      },
    },
  },

  -- Mason (AppLSP)
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "shellcheck",
        "harper-ls",
        "lua-language-server",
        "stylua",
        "css-lsp",
        "html-lsp",
        "typescript-language-server",
        "deno",
        "prettier",
        "clangd",
        "clang-format",
        "rust-analyzer",
        "bacon",
        "bacon",
        "bacon-ls",
        "cpptools",
        "js-debug-adapter",
        "firefox-debug-adapter",
        "js-debug-adapter",
        "biome",
        "codelldb",
      },
    },
  },
}
